version: '3.8'

services:
  pagopa-wallet:
    container_name: pagopa-wallet
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8200:8080"
    depends_on:
      - mongo
    networks:
      - pagopa-wallet-net

  mongo-express:
    container_name: pagopa-wallet-mongo-express
    image: mongo-express@sha256:1b23d7976f0210dbec74045c209e52fbb26d29b2e873d6c6fa3d3f0ae32c2a64
    env_file: ./docker/config/mongo/mongo-express.env
    ports:
      - "8201:8081"
    networks:
      - pagopa-wallet-net
    depends_on:
      - mongo

  mongo:
    container_name: pagopa-wallet-mongo
    image: mongo@sha256:7b225d4ae2df7cf98812f27f5d0d98054efaf9bfd4cc79c7e3e0bed1c1d3bf45
    env_file: ./docker/config/mongo/mongodb.env
    ports:
      - "28017:27017"
    networks:
      - pagopa-wallet-net
    healthcheck:
      test: echo "db.stats().ok" | mongo --quiet
      interval: 10s

  ecommerce-payment-methods:
    build:
      context: .
      dockerfile: ./docker/config/ecommerce-payment-methods/Dockerfile.ecommerce-payment-methods
    container_name: ecommerce-payment-methods
    volumes:
      - type: bind
        source: ./docker/config/ecommerce-payment-methods
        target: /config
        read_only: true
    ports:
      - "8089:3000"
    networks:
      - pagopa-wallet-net

  redis:
    container_name: wallet-redis
    image: redis@sha256:e422889e156ebea83856b6ff973bfe0c86bce867d80def228044eeecf925592b
    command: [ "sh", "-c", 'exec redis-server --requirepass "$$REDIS_PASSWORD"' ]
    ports:
      - "6379:6379"
    networks:
      - pagopa-wallet-net

  redis-insight:
    container_name: wallet-redis-insight
    image: redislabs/redisinsight@sha256:bbfe06e00282fc051bbfadd49286865e75b359baea62f0d56af0cb0d5684b942
    ports:
      - "8001:8001"
    networks:
      - pagopa-wallet-net

  pagopa-npg-mock:
    build:
      context: .
      dockerfile: ./docker/config/npg-mock/Dockerfile.npg-mock
    container_name: pagopa-npg-mock
    volumes:
      - type: bind
        source: ./docker/config/npg-mock
        target: /config
        read_only: true
    ports:
      - "3000:3000"
    networks:
      - pagopa-wallet-net

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest@sha256:d449d953a1c5bd1e26c800744a65c451e88f3387b696e02e3e2e79a995c3105b
    container_name: pagopa-wallet-azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - $PWD/.data:/opt/azurite/folder
    networks:
      - pagopa-wallet-net

  azurite-init:
    container_name: pagopa-wallet-azurite-init
    build:
      context: azurite/
      dockerfile: Dockerfile
    depends_on:
      - storage
    environment:
      QUEUE_EXPIRATION_WALLET: pagopa-wallet-expiration-queue
    networks:
      - pagopa-wallet-net

networks:
  pagopa-wallet-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1


