parameters:
  # Required
  - name: "ENV_FILE"
    type: string
  - name: "API_TEST_FILE"
    type: string
  - name: "TEST_FILE_PREFIX"
    type: string
  - name: "WALLET_TOKEN_TEST"
    type: string
  - name: 'TEST_DISPLAY_NAME'
    type: string
  - name: 'MIGRATION_API_KEY_TEST'
    type: string
    default: ""
  - name: 'MIGRATION_CSTAR_API_KEY_TEST'
    type: string
    default: ""
steps:
  - script: |
      yarn global add newman
    displayName: 'Newman installation'
  - script: |
      newman run ${{ parameters.API_TEST_FILE }} -e ${{ parameters.ENV_FILE }} --env-var WALLET_TOKEN_TEST=${{ parameters.WALLET_TOKEN_TEST }} --env-var MIGRATION_API_KEY_TEST=${{ parameters.MIGRATION_API_KEY_TEST }} --env-var MIGRATION_CSTAR_API_KEY_TEST=${{ parameters.MIGRATION_CSTAR_API_KEY_TEST }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml
    displayName: ${{ parameters.TEST_DISPLAY_NAME }}
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
