apiVersion: v2
name: wallet
description: Microservice that handles crud operations on wallet resources
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
