apiVersion: v2
name: wallet
description: Microservice that handles crud operations on wallet resources
type: application
version: 1.0.3
appVersion: 1.0.3
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
